language: python
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    python: 3.6
  exclude:
  - os: osx
    language: generic
    env: PYTHONPATH=/Library/Python/3.6/site-packages/
    dist: trusty
    sudo: required
    python: 3.6
cache: pip
install: 
  - pip install -r src/requirements.txt
  - pip install coveralls
script: 
  - python src/run_tests.py
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then coverage run --source=src/plasoscaffolder src/run_tests_for_coverage.py test ; fi
after_success:
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then coveralls ; fi
