language: python
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    python: 3.6
  - os: osx
    dist: trusty
    sudo: required
    python: 3.6
cache: pip
install:
  - ./config/travis/install.sh
script: 
  - python run_tests.py