language: python
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    python: 3.6
  - os: osx
    language: generic
    env: PYTHONPATH=/Library/Python/3.6/site-packages/
install:
  - pip install .
  - pip install -r requirements.txt
script: pytest