language: python
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    python: 3.6
  - os: osx
    language: generic
    env: PYTHONPATH=/Library/Python/3.6/site-packages/
    dist: trusty
    sudo: required
    python: 3.6
cache: pip
install: "pip install -r src/requirements.txt"
script: 
  - PYTHONPATH=${PYTHONPATH}:. src/run_tests.py
  - if test `uname -s` = 'Linux' && test ${TRAVIS_PYTHON_VERSION} = "3.6"; then coverage run --source=plasoscaffolder --omit="*test_*,*__init__*,*test_lib*" ./run_tests.py; else ./run_tests.py; fi
after_success:
  - if test `uname -s` = 'Linux' && test ${TRAVIS_PYTHON_VERSION} = "3.6"; then coveralls --verbose; fi