language: python
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    python: 3.6
  - os: osx
    language: generic
    env: PYTHONPATH=/Library/Python/3.6/site-packages/
    dist: trusty
    sudo: required
    python: 3.6
cache: pip
install: 
  - pip install -r src/requirements.txt
  - pip install coveralls
script: 
  - python src/run_tests.py
  - coverage run --source=./src/plasoscaffolder ./src/run_tests test
after_success:
  coveralls